// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get a list of all active categories
	// (GET /category/list-active-categories)
	GetAllActiveCategories(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAllActiveCategories operation middleware
func (siw *ServerInterfaceWrapper) GetAllActiveCategories(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllActiveCategories(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/category/list-active-categories", wrapper.GetAllActiveCategories)
}

type GetAllActiveCategoriesRequestObject struct {
}

type GetAllActiveCategoriesResponseObject interface {
	VisitGetAllActiveCategoriesResponse(w http.ResponseWriter) error
}

type GetAllActiveCategories200JSONResponse []CategoryResponse

func (response GetAllActiveCategories200JSONResponse) VisitGetAllActiveCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllActiveCategories500ApplicationProblemPlusJSONResponse Problem

func (response GetAllActiveCategories500ApplicationProblemPlusJSONResponse) VisitGetAllActiveCategoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get a list of all active categories
	// (GET /category/list-active-categories)
	GetAllActiveCategories(ctx context.Context, request GetAllActiveCategoriesRequestObject) (GetAllActiveCategoriesResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetAllActiveCategories operation middleware
func (sh *strictHandler) GetAllActiveCategories(ctx *gin.Context) {
	var request GetAllActiveCategoriesRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllActiveCategories(ctx, request.(GetAllActiveCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllActiveCategories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAllActiveCategoriesResponseObject); ok {
		if err := validResponse.VisitGetAllActiveCategoriesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4RTzW7bPBB8FYLfd6tjqUljp7oZKVoE6MFIjkUPa2olM6BIZrkyKhh694KU7NqVkF4s",
	"ebU/s7MzR6lc451Fy0EWRxnUHhtIr4/AWDvqnjF4ZwPGmCfnkVhjytBl/MVf0HiDspCr9cNu/QnuVpW6",
	"3d2u8nu1qu7Xn0u5kNz5mBGYtK1lv5AWGryufmmA2O+dxTAt6BeS8K3VhKUsfsTJY4uf51S3e0XFsfeW",
	"3M5gE9uXGBRpz9pZWcjnr4/rh3wtxgTxBRm0ieOuFytTPL5NcCORo2F7xiZMSak0mnK2tMEQoMaZb/3M",
	"EmMAiKCL/7UNDFal8spRAywL2ZKeIzcwcBsuBmnLWCOlvpoNzuJjAoVP89iHwL8m/3Wl9PU08YxqerE+",
	"rVe56cE22ydRORJvLVKnbS3UIEo9aGRY5axUsdk+yYU8IIWh/OMyXz5E+M6jBa9lIe+W+TKPBwfeJ4ay",
	"sWWXGR34BhTrA95czCmOskaOj3hmiMgiSfIb8saYTcp/vIRFo2FS6W2ex4dyltGmLuC90Sr1yV5DxHmy",
	"3ZWq/iesZCH/y/4YNBvdmU2sOdFLpPSayu86sHDVBYOCkEnjAUsRWqUwhKo1Jont/l3UfrDPhyn690Cf",
	"XDmD7YXBlkCliDolC0YkmyVBhbZpgLqBcAHCjHuAMWI41qUo+r7vfwcAAP//Gx9twNQEAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
